### ISSUE TITLE
Nonsquare Matrices throw Bounds Error

### ISSUE THREAD

**Issue by AlCap23** [SciML/LinearSolve.jl#101]
It seems like `LinearSolve` can not handle non-square matrices. A MWE would be

```Julia
using LinearAlgebra
using LinearSolve

A = randn(8, 10)
x = randn(10)
b = A*x

ldiv!(x, svd(A), b) # works

prob = LinearProblem(A, b[:,1])
sol = solve(prob, SVDFactorization()) # Bounds error
```

This is repeatable for at least `QR` and `LU`.

**Comment by Wimmerer** [comment]
Was non-square `svd` added in 1.7? I get a `DimensionMismatch` on 1.6.

**Comment by Wimmerer** [comment]
The problem is (I think) https://github.com/SciML/LinearSolve.jl/blob/3ba3bc3d94ed307a16adabbbe079af8228fe79ea/src/common.jl#L90

This is not the right size.
