### ISSUE TITLE
Hypre/BoomerAMG wrapper?

### ISSUE THREAD

**Issue by learning-chip** [SciML/LinearSolve.jl#106]
https://github.com/hypre-space/hypre

In particular, [BoomerAMG](https://hypre.readthedocs.io/en/latest/solvers-boomeramg.html) only needs a general sparse matrix, without extra physical knowledge.

**Comment by Wimmerer** [comment]
Looks like we'd want to revive: https://github.com/jgoldfar/Hypre.jl
