### ISSUE TITLE
default branching to factorization on Diagonal type

### ISSUE THREAD

**Issue by vpuri3** [SciML/LinearSolve.jl#110]
Im passing in a `Diagonal |> DiffEqArrayOperator`  to `OrdinaryDffEq` with alg `SBDF3()` , and `LinearSolve`  is dispatching to `lu!`. 

```julia
diffusion = A |> Diagonal |> DiffEqArrayOperator
ode_prob = SplitODEProblem(diffusion, rhs!, û₀[1], tspan; saveat=tsave)
ensemble_sol = solve(ensemble_prob, SBDF3(), ensemble_type; dt=1e-2 kwargs...)
```
```julia
nested task error: MethodError: no method matching lu!(::Diagonal{Float64, Vector{Floa
t64}}, ::RowMaximum; check=false)
```

We can either add a case for Diagonal type in the default alg https://github.com/SciML/LinearSolve.jl/blob/main/src/default.jl but won't it be more robust if we can just figure out if whatever type is passed in has a predefined `ldiv!` and just use that? I think just having a kwarg `hasldiv!` would be very good

Would `ArrayInterface` be the right place to look?

**Comment by chriselrod** [comment]
Maybe `Tricks.static_hasmethod`? https://github.com/oxinabox/Tricks.jl

**Comment by vpuri3** [comment]
Thanks @chriselrod that's exactly what i was looking for! and thanks @oxinabox for such a cool package

**Comment by vpuri3** [comment]
@chriselrod FYI
https://github.com/SciML/LinearSolve.jl/pull/112#issuecomment-1086057410

**Comment by vpuri3** [comment]
ok the problem isn't exactly in `LinearSolve`. Sooo the `prepare_alg` function in `OrdinaryDiffEq` sets the linear solve algorithm in `SBDF3` to `LinearSolve.GenericLUFactorization{RowMaximum}(RowMaximum())`. 

https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L162-L183

```julia
julia> using DifferentialEquations.OrdinaryDiffEq

julia> n = 8; A = rand(n) |> Diagonal |> DiffEqArrayOperator; rhs! = (du,u,p,t) -> du; u0 = rand(n); tspan=(0,1);

julia> prob = SplitODEProblem(A, rhs!, u0, tspan);

julia> alg=OrdinaryDiffEq.DiffEqBase.prepare_alg(SBDF3(), prob.u0, prob.p, prob)
OrdinaryDiffEq.SBDF{8, true, LinearSolve.GenericLUFactorization{RowMaximum}, NLNewton{Rational{Int64}, Rational{Int64}, Rational{Int64}}, typeof(OrdinaryDiffEq.DEFAULT_PRECS), Val{:forward}, true, nothing, Nothing, Nothing}(LinearSolve.GenericLUFactorization{RowMaximum}(RowMaximum()), NLNewton{Rational{Int64}, Rational{Int64}, Rational{Int64}}(1//100, 10, 1//5, 1//5), OrdinaryDiffEq.DEFAULT_PRECS, nothing, nothing, :linear, 3, false)

julia> alg.linsolve
LinearSolve.GenericLUFactorization{RowMaximum}(RowMaximum())

```

and that doesn't fly well with `Diagonal` type. 
```julia
MethodError: no method matching lu!(::Diagonal{Float64, Vector{Float64}}, ::RowMaximum; check=false)```

**Comment by ChrisRackauckas** [comment]
This just means that `prepare_alg` should be checking if `prob.f isa AbstractDiffEqOperator` and if it is, specializing the `prepare_alg` on that instead of on the `jac_prototype`, since the Jacobian would then be defined directly by the characteristics of the operator.

**Comment by vpuri3** [comment]
i see it now. in `prepare_alg`, the branch https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L168-L171 never gets evaluated.

This 
```julia
julia> (prob.f isa SplitFunction && prob.f.f1 isa SciMLBase.AbstractDiffEqOperator)
false
julia> prob.f.f1
(::ODEFunction{true, DiffEqArrayOperator{Float64, Diagonal{Float64, Vector{Float64}}, typeof(SciMLBase.DEFAULT_UPDATE_FUNC)}, UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}) (generic function with 7 methods)
```

it should rather be
```julia
julia> (prob.f isa SplitFunction && prob.f.f1.f isa SciMLBase.AbstractDiffEqOperator)
true
```
