### ISSUE TITLE
Compatibility with Enzyme.jl?

### ISSUE THREAD

**Issue by ryanstoner1** [SciML/LinearSolve.jl#142]
Wondering if this package is or should eventually be a partial workaround of Enzyme's BLAS limitations. 
For example running the following from the test set causes Enzyme to crash for me (M1 Mac). 
```
using LinearSolve, LinearAlgebra, SparseArrays
using Test
import Random

n = 8
A = Matrix(I,n,n)
b = ones(n)
A1 = A/1; b1 = rand(n); x1 = zero(b)
dA1 = zero(A1)
db1 = zero(b1)
dx1 = zero(x1)

function test1(A1,b1,x1)  
    _prob = LinearSolve.LinearProblem(Diagonal(A1), b1; u0=x1)
    y = solve(_prob)
    return sum(y.u)
end
Enzyme.autodiff(test1,Active,Duplicated(A1,dA1),Duplicated(b1,db1),Duplicated(x1,dx1))

```

**Comment by ChrisRackauckas** [comment]
Right now there is no way to externally provide derivative rules to Enzyme, but the moment that is possible, SciML will support Enzyme everywhere.

**Comment by ryanstoner1** [comment]
That makes sense. Thank you for the response!
