### ISSUE TITLE
Use FastLapackInterface backend

### ISSUE THREAD

**Issue by YingboMa** [SciML/LinearSolve.jl#150]
https://github.com/DynareJulia/FastLapackInterface.jl

FastLapackInterface.jl would allow us to eliminate all allocations.

**Comment by ChrisRackauckas** [comment]
@Wimmerer could we get some help here?

**Comment by Wimmerer** [comment]
Yep, I'll look at it later today.

**Comment by Wimmerer** [comment]
Since this adds no additional deps except FastLapackInterface.jl itself should we add it as a dependency?

**Comment by ChrisRackauckas** [comment]
I think so.

**Comment by ChrisRackauckas** [comment]
No worries, that's great.

**Comment by Wimmerer** [comment]
Closed by https://github.com/SciML/LinearSolve.jl/pull/153. Some improvements still to be made (we could allow passing in the workspace, and we should support resizing the workspace as necessary) as well as additional tests.
