### ISSUE TITLE
"Fast" solvers are slow for dense, complex matrix

### ISSUE THREAD

**Issue by simonp0420** [SciML/LinearSolve.jl#159]
According to the documentation, `RFLUFactorization` is supposed to be faster than backslash for matrices on the order of a few hundred.  I did some quick benchmarking and I'm not finding this to be the case.  Am I doing something wrong?
```
using LinearSolve, BenchmarkTools

n = 200
A = rand(ComplexF64, n, n)
b = rand(ComplexF64, n)

@btime $A\$b ; # 474 μs

prob = LinearProblem(copy(A), copy(b))
@btime solve($prob, LUFactorization()); # 477 μs. As expected, similar to `\`

prob = LinearProblem(copy(A), copy(b))
@btime solve($prob); # 20.4 ms.  Not sure what method is used here.

prob = LinearProblem(copy(A), copy(b))
@btime solve($prob, RFLUFactorization()); # 21.8 ms.  Forty-some times slower than BLAS LU

prob = LinearProblem(copy(A), copy(b))
method = LinearSolve.FastLUFactorization()
@btime solve($prob, $method); # 14.9 ms .  Better but still way slower than BLAS

using LinearAlgebra
BLAS.get_config()
#=
LinearAlgebra.BLAS.LBTConfig
Libraries: 
└ [ILP64] libopenblas64_.so
=#
```
I'm running Julia v1.7.3 and LinearSolve v1.22.1

Also, I found that `FastLUFactorization` is not exported so I had to invoke it as `LinearSolve.FastLUFactorization()`.

**Comment by ChrisRackauckas** [comment]
How many Julia threads are open on your system? Show `versioninfo()`

**Comment by ChrisRackauckas** [comment]
@chriselrod

**Comment by Wimmerer** [comment]
LUFact and FastLUFact should have approximately the same time for the initial solve I think? They're both `getrf` right?

**Comment by chriselrod** [comment]
Those are complex matrices. 
You could make a PR to add actual complex support to RecursiveFactorization.

Or wait for the LoopVectorization rewrite to be finished. 
Development is active there, but it will still be a while.

**Comment by ChrisRackauckas** [comment]
Oh RecursiveFactorization.jl doesn't have a specialization for complex matrices? I didn't know that. We should specialize the default algorithm on that fact and document it then. What exactly is the issue, that it's only fast for Float32 and Float64?

**Comment by simonp0420** [comment]
8 threads on my system:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by ChrisRackauckas** [comment]
> LUFact and FastLUFact should have approximately the same time for the initial solve I think? They're both getrf right?

Yes, they should. I mean, FastLUFact is just an alternative interface to BLAS that skips rebuilding the workspace each time, so it's not that it should be as fast as BLAS, it is a BLAS call 😅 . So that's a pretty confusing result here that needs to get explored a bit more.

I opened a PR that tweaks the default algorithms a bit more: https://github.com/SciML/LinearSolve.jl/pull/160 . Though I think we should figure out what's going on with FastLUFactorization.

**Comment by chriselrod** [comment]
> Oh RecursiveFactorization.jl doesn't have a specialization for complex matrices? I didn't know that. We should specialize the default algorithm on that fact and document it then. What exactly is the issue, that it's only fast for Float32 and Float64?

LoopVectorization.jl only supports `Union{Bool,Base.HWReal}`.

**Comment by simonp0420** [comment]
I'm happy to wait for the rewrite.  However, I'm also not seeing the advertised speedup on Float64:

|  Algorithm | n = 200 | n = 500 | n = 2000 |
|:------------:|:--------------:|:------------:|:-----------------:|
| Backslash |  0.2       |     1.3   |          29     |
| (Default)   |   0.2       |     1.2   |         29      |
| LUFactorization | 0.2 | 1.3     |     29   |
| RFLUFactorization | 0.2 | 1.2 | 48 |
| Fast LUFactorization| 0.3 | 2.1 | 53.7 |

`n` is the order of the matrix and the table entries are times in msec reported by `@btime`.

**Comment by ChrisRackauckas** [comment]
`&& <= length(500)`

https://github.com/SciML/LinearSolve.jl/blob/main/src/default.jl#L17

**Comment by simonp0420** [comment]
So the default algorithm was selected to be `RFLUFactorization` for the n = 200 and n=500 cases?   Sounds good.  But why isn't it any faster than backslash in those cases?

**Comment by Wimmerer** [comment]
I need to investigate what's happening in FastLUFactorization. This should be taking exactly as long as Backslash, until you do a re-solve where it should be faster.

**Comment by ChrisRackauckas** [comment]
> But why isn't it any faster than backslash in the two smaller cases?

Can you run the benchmarks? https://github.com/JuliaLinearAlgebra/RecursiveFactorization.jl/blob/master/perf/lu.jl

And share your CPU? It at least was about 2x faster for things we tested https://github.com/JuliaLinearAlgebra/RecursiveFactorization.jl/pull/28

**Comment by simonp0420** [comment]
Thanks for your fast response on this issue.  Looking forward to using this for complex matrices (ubiquitous is my work) in the future.

**Comment by chriselrod** [comment]
How many threads did you use in your benchmark?

**Comment by ChrisRackauckas** [comment]
Yup so that fits the heuristic of the default algorithm:

```
(length(b) <= 100 || (isopenblas() && length(b) <= 500))
```

If <100 or if openBLAS less than 500, use RecursiveFactorization. Otherwise use the (provided) BLAS.  So I think that's pretty close to what you measure. 

I wonder if we could provide MKLLUFactorization which doesn't overload LBT?

**Comment by simonp0420** [comment]
> I'd also be interested in seeing single threaded plots of both
Here is the plot for single-threaded vs OpenBLAS:
![lu_float64_1 7 3_skylake_1cores_OpenBLAS](https://user-images.githubusercontent.com/4294361/179640133-2efb08b0-b913-41f4-afe7-b132b35f504e.png)
and here is the corresponding plot for MKL:
![lu_float64_1 7 3_skylake_1cores_MKL](https://user-images.githubusercontent.com/4294361/179640173-ba016a3e-4867-4322-b6a9-afea969862ad.png)

**Comment by ChrisRackauckas** [comment]
Let's take benchmarking discussions to https://github.com/SciML/LinearSolve.jl/issues/166 . MKL to https://github.com/SciML/LinearSolve.jl/issues/164 . This for FastLUFactorization being slow.

**Comment by simonp0420** [comment]
I'm almost done with some similar runs on Windows.  Want me to put the plots in a comment in #166?

**Comment by ChrisRackauckas** [comment]
Yes please!

**Comment by ChrisRackauckas** [comment]
FastLUFactorization in v2 is optimized to be non-allocating and all, see https://github.com/SciML/LinearSolve.jl/pull/313/ . But it doesn't seem to make a real difference since that workspace is not the main cost, and the `copyto!` can be slower. If you're solving multiple times, then maybe it's faster, but at least on v2 it doesn't look to be an implementation thing.
