### ISSUE TITLE
Hypre wrapper

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#167]
https://github.com/fredrikekre/HYPRE.jl

**Comment by Wimmerer** [comment]
How do we do this? HYPRELinearSolve.jl package?

**Comment by ChrisRackauckas** [comment]
yup

**Comment by ChrisRackauckas** [comment]
yup

**Comment by Wimmerer** [comment]
Okay sounds good. SuperLU_DIST wrapper is coming along too so we'll have that as well by the end of the summer I believe.

**Comment by Wimmerer** [comment]
I'm going to have to figure out the sparse infrastructure here soon... Conversions and stuff will get nasty with distributed wrappers and solvers and such.
