### ISSUE TITLE
LinearSolve default handling for non-square

### ISSUE THREAD

**Issue by alex-s-gardner** [SciML/LinearSolve.jl#177]
If I want to solve a 12 parameter model:

```
A = rand(100,12)
b = rand(100,1)
x = A\b
```

works just fine in Julia or matlab. But the following does not work in LinearSolve:

```
using LinearSolve
prob = LinearProblem(A,b)
sol = solve(prob)
```
as it requires A to be a square matrix. 

I'm just curious why this is.

**Comment by vpuri3** [comment]
what \ is doing is a linear least squares solve.

**Comment by ChrisRackauckas** [comment]
The default algorithm choice is just forgetting to check for square before choosing lu. We should add that bit.

**Comment by ChrisRackauckas** [comment]
`sol = solve(prob, QRFactorization)`
