### ISSUE TITLE
Factorization runs twice for sparse matrices

### ISSUE THREAD

**Issue by j-fu** [SciML/LinearSolve.jl#179]
Hi,
In
https://github.com/SciML/LinearSolve.jl/blob/main/src/common.jl#L100

`is_fresh` is set to true regardless of the fact that e.g. for `UMFPACKFactorization()` a full factorization already has been performed.

As a consequence, when replacing `A\b` by `solve(LinearProblem(A,b))`,
performance becomes worse.

**Comment by ChrisRackauckas** [comment]
@Wimmerer were you going to take a look at this?

**Comment by ChrisRackauckas** [comment]
This was solved awhile ago by ArrayInterface updates.
