### ISSUE TITLE
saving estimated covariance matrices?

### ISSUE THREAD

**Issue by YSanchezAraujo** [SciML/LinearSolve.jl#189]
Hi all, 

Apologies if this is somehow already possible, or has already been addressed. In solving a system Ax=b, it's usually of interest having error bars for the estimated x. Implementing this naively is straight forward but can end up taking a lot of compute time when the matrix A has many columns. Wondering if there's already builtin functionality to save the quantity inv(A'A) ? I'm assuming the algorithms used here don't actually perform that computation but estimate it somehow.

**Comment by ChrisRackauckas** [comment]
You'd just do a QR and cache the QR.

**Comment by YSanchezAraujo** [comment]
ah ok thanks!
