### ISSUE TITLE
Dealing with (near) rank deficiency efficiently?

### ISSUE THREAD

**Issue by NicolasL-S** [SciML/LinearSolve.jl#215]
Maybe this issue should be directed towards LinearAlgebra.jl.

Iterative solvers require lots of linear solves Ax=b, but these are often quite useless when A is ill-conditioned. Looking at some packages, I have seen some people handling the problem by checking the condition number doing something like:

```
if cond(A) < threshold
    solve Ax = b
else
    do something else
end
```
The problem is that computing cond(A) is often much longer than doing the actual solve. Is there a faster way of doing this? Also, LAPACK will still spend time checking whether A is full-rank. Could this be avoided?

An alternative could be 
```
try
    solve Ax = b
catch
    do something else
end
```
Here, the problem is that a near rank-deficient A will not error (and we have no control over the tolerance used to assess whether solve Ax = b has failed or not). (also, try catch takes time and should generally be avoided as I've heard).

**Comment by NicolasL-S** [comment]
I think I have found an acceptable solution to my problem. I will explain it briefly in case someone thinks there is something wrong with it, it could be improved somehow, or if someone has a similar issue.

In brief, the trick is to 1) find a substitute to cond() and 2) use try-catch.

cond() is slow because it uses opnorm(). Instead, computing it by hand using norm() is faster, especially for small matrices (just reporting the median times for conciseness):
```
using LinearAlgebra, BenchmarkTools
A = rand(10,10);
@benchmark cond(A)
 Time  (median):     10.500 μs              ┊ GC (median):    0.00%

@benchmark norm(A)*norm(inv(A))
 Time  (median):     3.322 μs               ┊ GC (median):    0.00%

A = rand(100,100);
@benchmark cond(A)
 Time  (median):     2.219 ms               ┊ GC (median):    0.00%

@benchmark norm(A)*norm(inv(A))
 Time  (median):     1.544 ms               ┊ GC (median):    0.00%
```
The results are comparable enough to serve as diagnostic tool. Here I generated 5*5 quite ill conditioned matrices:
```
using Plots
n = 100000;
conds = zeros(n);
my_conds = zeros(n);
for i in 1:n
    M = rand(5, 5)
    conds[i] = cond(M)
    my_conds[i] = norm(M) / abs(det(M))
end
scatter(log.(conds), log.(my_conds))
```
![This is an image](https://github.com/NicolasL-S/NicolasL-S/blob/main/cond_norm.png?raw=true)

Can we do better? The problem with the condition number is the need to compute the inverse. To avoid it, a different sign of an ill-conditioned matrix would be a very small determinant. Of course, a small determinant may be simply due to a matrix having small entries. This naturally suggests an alternate measure: The norm of the matrix divided by the absolute value of its determinant. I have compute this alternate measure for the same random matrices. This new "condition number", cond2 for short, is on the vertical axis:

![This is an image](https://github.com/NicolasL-S/NicolasL-S/blob/main/cond2.png?raw=true)

Apart from the noise and the sligtly smaller values, cond2 seems to generate mostly positive outliers (i.e. false positive of ill-conditioning), but no apparent false negatives. Hence, cond2 may lead to being overly cautious. To reduce false positives, we could also fall back on cond() when cond2 is above some threshold.

Finally, the determinant may be easily computed using the factorized matrix. A try-catch statement allows us to compute it safely. Comparing the compute times for a 10*10 matrix:
```
A = rand(10, 10);
b = rand(10);

@benchmark A\b
 Time  (median):     2.170 μs               ┊ GC (median):    0.00%

@benchmark begin
	cond(A)
	A\b
end
 Time  (median):     13.500 μs              ┊ GC (median):    0.00%

@benchmark try
		fA = factorize(A)
		cond2 = norm(A)/abs(det(fA))
		fA\b
catch
end
 Time  (median):     2.340 μs               ┊ GC (median):    0.00%
```

Rather than taking 6 times longer using cond(), this approach increases compute time by only 8%.

**Comment by NicolasL-S** [comment]
To those interested, I have solved my issue in a very easy way.
1. Compute the svd of the matrix.
2. Compute the condition number = largest / smallest singular value.
3. Solve the system using the same svd.

**Comment by oscardssmith** [comment]
Just for the record, this isn't a great solution since the svd is a relatively expensive way of solving a linear problem.

**Comment by vpuri3** [comment]
Computing the SVD indeed very expensive, and I wont recommend that solution as you can't tell apriori how long this method would take. Unfortunately, there is no magic pill to numerical linear algebra, and there are no general purpose methods for solving *large* systems. 

Krylov methods aren't that great either unless you have a preconditioner. As the name suggests a preconditioner "conditions" the linear problem, ie solves a problem with a reduced condition number allowing krylov solvers to converge orders of magnitude faster.

**Comment by ChrisRackauckas** [comment]
If this is a more robust solver, `RobustSVD()` might be a nice algorithm to have around. Not every algorithm is about being fast: some are about being stable. Speed vs stability is a trade-off and a good library should have options that let the user choose how to best use the trade-off there.

**Comment by ChrisRackauckas** [comment]
That pseudocode seems a bit off though @NicolasL-S. You compute the condition number but then don't use it?

**Comment by NicolasL-S** [comment]
Thanks for the help! I was writing my own Anderson method for fixed points iterations (I know some already exist in Julia). Similar to the LBFGS, the method accumulates past iterates. Sometimes the matrix A (dense, but not that large) may become quite ill conditioned. A way to address this is keeping only recent iterates when its condition number becomes too high. A description of the algorithm would go something like

```
while the condition number of A is too high:
    compute the SVD of A
    use the SVD to compute the condition number
    if the condition number is too high, reduce the size of A by dropping the oldest iterate
end
Use the svd to solve Ax=b
```

That said, I'm not sold on this solution yet (maybe using QR and not reducing A would also work well, I haven't tried yet). Since the goal is accelerating convergence, this linear solve (and computation of the condition number) shouldn't start dominating in terms of compute time. I see your point about the SVD being slow. I did it this way because this is what is implemented in dense.jl for the 2-norm condition number, so I figured the same time would be needed using cond(A). Faster solutions would definitely better. Note also that precision may be important since numerical errors accumulate iteratively and slow convergence.

**Comment by ChrisRackauckas** [comment]
I don't think there's something actionable here? We now have a system for specifying conditioning, and we have `SVDFactorization`, and I think that's all of the tools here. If there is a `RobustSVD` algorithm (which "reduce the size of A by dropping the oldest iterate" doesn't sound too generalizable) then it would be nice to see, but the description sounds like it's a solution for a specific problem that is essentially changing the problem, so I don't see a robustsvd here.
