### ISSUE TITLE
Avoid (unconditional) precompiling of code that has GPL dependecies

### ISSUE THREAD

**Issue by andreasnoack** [SciML/LinearSolve.jl#224]
If a user would like to run with a non-GPL version of Julia then precompilation would probably fail because of https://github.com/SciML/LinearSolve.jl/blob/0a3d5ba2f6db5894a13ae8cce717714bdcadf2e4/src/LinearSolve.jl#L64-L68 so it would be useful to make those lines conditional on inclusion of the sparse libraries.

**Comment by ChrisRackauckas** [comment]
We can set that up with Preferences like OrdinaryDiffEq

**Comment by DilumAluthge** [comment]
I don't think we need Preferences here, do we? We can just check the value of `Base.USE_GPL_LIBS`.

**Comment by DilumAluthge** [comment]
Okay, #238 now uses `Preferences`. If the user does not specify the preference, we default to the value of `Base.USE_GPL_LIBS`.
