### ISSUE TITLE
Fix common argument handling

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#23]
Common arguments should be handled as kwargs in init/solve, not in the algorithm.

https://diffeq.sciml.ai/stable/basics/common_solver_opts/

`reltol`, `abstol`, `verbose` are ones I've seen that need to get moved.

@vpuri3

**Comment by vpuri3** [comment]
`maxiter` should stay within KSP wrappers?

**Comment by ChrisRackauckas** [comment]
No, we should handle `maxiters` as a common argument, and within the Krylov.jl solve context realize that the wrapped library uses a different name and do the translation under the hood. That way users can switch algorithms without having the change argument names around.

**Comment by vpuri3** [comment]
close?

**Comment by ChrisRackauckas** [comment]
💥
