### ISSUE TITLE
Insert default preconditioners

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#26]
The default preconditioners are then composed with any preconditioner placed in there, like is done in https://github.com/SciML/DiffEqBase.jl/blob/v6.76.0/src/linear_nonlinear.jl#L219-L226 . This is shown to almost always speed up the convergence.

**Comment by vpuri3** [comment]
how do we want to go about this? cache is initialized with default scalevector preconditioner and then we compose that with alg.Pl,Pr? what should we initialize ScaleVector with - norm(b) or something?

**Comment by ChrisRackauckas** [comment]
Yeah, see how it's done in the other repo. ComposePreconditioner make it easy to combine preconditioners, and then this one is added directly to whatever is put in, or if nothing this is the only one that is ran. That's a strategy taken from SUNDIALS because it generally gives a pretty good convergence boost, though it might be good to have a way to disable it just in case.

Ping @YingboMa if you need help on it.
