### ISSUE TITLE
The LinearSolve.jl interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#3]
- [x] `LinearProblem(A,b,p=SciMLBase.NullParameters();u0=nothing,kwargs...)` where kwargs forward to solve
- [ ] `ShiftedLinearProblem(A,b,gamma,p=SciMLBase.NullParameters();u0=nothing,kwargs...) = LinearProblem(WOperator,...)`
- [ ] `solve(prob,alg;reltol, abstol, weights, prec)`
- [x] `cache = init(prob,alg; kwargs...)` where `solve = init -> solve!(cache)`
- [ ] Functions on cache:
    - [x] `set_A!(cache,A)`
    - [x] `set_b!(cache,b)`
    - [x] `set_p!(cache,p)`
    - [ ] `set_prec(cache,prec)`
    - [ ] update_prec!(cache) = set_prec!(cache,cache.prec(cache)...)` 
- [x] The cache should have fields `A`, `cacheval`, `isfresh`, `pr`, and `pl`
- [ ] The factorization alg should just have the factorization function
- [ ] IterativeSolversAlg should set the iterable to cacheval, factorization methods should store the factorized `A` there.
- [ ] Preconditioner functions:
    - [ ]  `@set cache.prec = f(Val{:init}, cache)` for initialization
    - [ ] preconditioner function is `f(cache) -> (pl,pr)` user-defined.

[Linear.pdf](https://github.com/SciML/LinearSolve.jl/files/6802305/Linear.pdf)

**Comment by YingboMa** [comment]
Do we need `ShiftedLinearProblem` if there's `LinearProblem(WOperator,...)`?

**Comment by ChrisRackauckas** [comment]
We can leave that for us to figure out. @EdelmanJonathan won't handle that part.

**Comment by ranocha** [comment]
`resize!` would also be a great functionality for the cache, for example in the context of PDEs and adaptive mesh refinement.

**Comment by ChrisRackauckas** [comment]
yes, good point.

**Comment by vpuri3** [comment]
should `LinearCache` also have fields for present solution `u`, and iteration count `iter` (set to 0 for factorizations)?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by vpuri3** [comment]
what's `weights` in the third task: `solve(prob,alg;reltol, abstol, weights, prec) `?

**Comment by ChrisRackauckas** [comment]
Those are the weights supposed to be used in the scaled preconditioners.
