### ISSUE TITLE
Sparse LU benchmarking

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#359]
Now with https://github.com/SciML/LinearSolve.jl/issues/357 kicked off, we should create a similar benchmark in the sparse space. Maybe using https://github.com/JuliaSparse/MatrixMarket.jl to read https://math.nist.gov/MatrixMarket/formats.html#MMformat. 
@Wimmerer do you have matrix sets like https://sparse.tamu.edu/Gset and the NIST one (where do you even find that?) easy to just loop through? If so we can just do a timing on all of them and create a few plots. After that, we can get it onto https://docs.sciml.ai/SciMLBenchmarksOutput/stable/

**Comment by j-fu** [comment]
Hi, I did some sparse benchmarking:

https://j-fu.github.io/marginalia/julia/scalingtest/


IMHO performance  quite a bit depends on structural info, eg 1D/2D/3D. The kron trick used in the notebook gives reasonably typical matrices for scalar FD/FV/FE.

Just gone cycling - will be back at my computer next week.

**Comment by ChrisRackauckas** [comment]
That would be good to add to the SciMLBenchmarks as well. Could you take the time to PR it today? Shouldn't take more than an hour. I'd still like to see other sparse matrices in a benchmarkable format in order to setup a better default algorithm, but the scaling PDE ones are definitely useful.

**Comment by j-fu** [comment]
Already on my smartphone... Will PR when I'll be back.

**Comment by j-fu** [comment]
See #365 

![sparselubench](https://github.com/SciML/LinearSolve.jl/assets/9221937/fcf7dfce-2ae2-4550-b549-e7f5180ac3c0)

**Comment by briochemc** [comment]
Potentially relevant paper I stumbled upon recently comparing UMFPACK vs Paridso vs MUMPS using Matrix Market matrices relevant to finite-element methods AFAIU: 

> Pedroso DM. Caveats of three direct linear solvers for finite element analyses. *Int J Numer Methods Eng.* 2024;125(17):e7545. [doi: 10.1002/nme.7545](https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.7545)

**Comment by ChrisRackauckas** [comment]
We have benchmarks growing at SciMLBenchmarks, so I'll close this here.
