### ISSUE TITLE
Release 2.19.0 breaks my code

### ISSUE THREAD

**Issue by ufechner7** [SciML/LinearSolve.jl#429]
I am running a ModelingToolkit simulation multithreaded, same model, different parameters.
This worked fine before 2.19.0, but not any longer.

Luckily I found out I can just add MKL to my project and it works again.

But why is multithreading only working with MKL and not with OpenBLAS?

**Comment by ChrisRackauckas** [comment]
OpenBLAS is multithreaded but it's really bad at multithreading so it's almost always worse. We don't change anything about OpenBLAS's parameters, it's just the defaults.

What size model is it? What linear solver is chosen? Is it sparse?

> Release 2.19.0 breaks my code

Can you share the stack trace and error message?

**Comment by ufechner7** [comment]
Well, there is no stack trace. It works, but only single threaded... The symplified model looks like this:
```
Model sys with 5 equations
States (5):
  ω(t)
  Uest(t)
  Pgc(t)
  y(t) [defaults to 7.0]
  yd(t) [defaults to 0]
Parameters (15):
  J [defaults to 4.047e7]
  Ku [defaults to 2.25e-7]
  λnom [defaults to 8.0]
  R [defaults to 63.0]
  Γest [defaults to 1.0]
  Δα_est [defaults to 0.0]
⋮
Incidence matrix:5×10 SparseArrays.SparseMatrixCSC{Num, Int64} with 16 stored entries:
 ×  ⋅  ×  ⋅  ⋅  ×  ⋅  ⋅  ⋅  ⋅
 ×  ×  ×  ⋅  ⋅  ⋅  ×  ⋅  ⋅  ⋅
 ×  ×  ×  ⋅  ⋅  ×  ⋅  ×  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ×  ⋅  ⋅  ⋅  ×  ⋅
 ⋅  ⋅  ⋅  ⋅  ×  ⋅  ⋅  ⋅  ⋅  ×
```
I am calling the solver like this:
```
sol = solve(prob, Rodas5(), dt=dt, tstops=tstops, abstol=tol, dtmax=1, reltol = tol, saveat=ts)
```

**Comment by ChrisRackauckas** [comment]
Okay, that's not "breaks my code". Please in the future be precise with that. We know MKL is faster. I want it to make it a default, but right now `using MKL` is actually breaking.

**Comment by ufechner7** [comment]
Well, if I an indirect dependency of my project gets updated and multithreading stops to work, I would call this breaking. MKL is not 7 times faster than OpenBLAS. There is something else going on.

**Comment by ChrisRackauckas** [comment]
Sorry but that was literally the only thing changed in that release. See https://github.com/SciML/LinearSolve.jl/releases/tag/v2.19.0. The entirety of the code changes are https://github.com/SciML/LinearSolve.jl/compare/v2.18.0...v2.19.0

**Comment by ufechner7** [comment]
Well, but this has a huge impact...

**Comment by ChrisRackauckas** [comment]
Then advocate for LinearAlgebra to improve by shipping MKL instead of OpenBLAS. I'm with you on that, but it needs to get fixed.
