### ISSUE TITLE
Allow Metal 1.0?

### ISSUE THREAD

**Issue by KristofferC** [SciML/LinearSolve.jl#480]
This package holds back Metal from updating.

**Comment by ChrisRackauckas** [comment]
How so? This package does not have a dependency on Metal and it doesn't have any unmerged CompatHelper PRs.

**Comment by KristofferC** [comment]
https://github.com/SciML/LinearSolve.jl/blob/22f4f0b76591305eab88e1af80edf40f46d93e15/Project.toml#L92

**Comment by ChrisRackauckas** [comment]
Interesting, is CompatHelper broken for weak deps?

**Comment by ChrisRackauckas** [comment]
Tested locally, it's fine. Bumped

**Comment by KristofferC** [comment]
Maybe not upgraded to handle them?
