### ISSUE TITLE
`QRFactorization` throws when given singular matrices

### ISSUE THREAD

**Issue by oscardssmith** [SciML/LinearSolve.jl#489]
this gives a `LAPACKException` because `A` is singular and `QRFactorization` defaults to `NoPivot` instead of `ColumnNorm`.
```
using LinearSolve
A = vcat(rand(1,2), zeros(2,2)), rand(3))
solve(LinearProblem(A, QRFactorization())
```

I'm not sure if there's a good way to detect whether the factorization is singular in this case, but we should do so and return a failure rather than throw an error.

**Comment by avik-pal** [comment]
Fixed in the latest release

![image](https://github.com/SciML/LinearSolve.jl/assets/30564094/da0f03da-e3d9-4db1-9c04-aacfa67aa192)
