### ISSUE TITLE
add choleskyqr factorization methods

### ISSUE THREAD

**Issue by oscardssmith** [SciML/LinearSolve.jl#496]
as described in https://arxiv.org/pdf/2111.11148v2, these algorithms can be faster than traditional qr, but don't handle poorly conditioned matrices as well.

**Comment by ChrisRackauckas** [comment]
that's [NormalCholeskyFactorization](https://docs.sciml.ai/LinearSolve/stable/solvers/solvers/#LinearSolve.NormalCholeskyFactorization)?

**Comment by oscardssmith** [comment]
ah. I think you're right. I didn't see the connection since the paper described this as a type of qr method so I was looking for qr algorithms.
