### ISSUE TITLE
Pardiso wrappers

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#5]
Uses https://github.com/JuliaSparse/Pardiso.jl . Starter code:

https://github.com/SciML/DiffEqBase.jl/blob/master/src/init.jl#L265-L378

**Comment by ChrisRackauckas** [comment]
@vpuri3 if you still have one last push to do, I think this would be a good last one to solve. Set it up in `@requires` form.

**Comment by vpuri3** [comment]
i don't know what `@requires` is. is this it: https://github.com/JuliaPackaging/Requires.jl ?

**Comment by ChrisRackauckas** [comment]
yes
