### ISSUE TITLE
stable documentation link is broken

### ISSUE THREAD

**Issue by simonbyrne** [SciML/LinearSolve.jl#80]
https://linearsolve.sciml.ai/stable/

**Comment by ChrisRackauckas** [comment]
Yeah... I thought it would build with 1.0. I don't know why it didn't.

**Comment by ChrisRackauckas** [comment]
https://linearsolve.sciml.ai/dev/

Documenter hasn't been adding tags for some reason.

**Comment by ChrisRackauckas** [comment]
Fixed.
