### ISSUE TITLE
nonlinear system??

### ISSUE THREAD

**Issue by vpuri3** [SciML/LinearSolve.jl#86]
https://github.com/SciML/LinearSolve.jl/blob/dacd618607adc061215e61e16320dcac29c44e3b/docs/src/solvers/solvers.md?plain=1#L3-L8

nonlinear system arising from `prob::LinearProblem`?

**Comment by ChrisRackauckas** [comment]
Haha thanks

**Comment by vpuri3** [comment]
https://github.com/SciML/LinearSolve.jl/blob/main/docs/src/solvers/solvers.md?plain=1#L1 
line 1: `# [Linear System Solvers](@id nonlinearsystemsolvers)`

**Comment by ChrisRackauckas** [comment]
The amount that started as a copy paste from NonlinearSolve.jl should not be underestimated.
