### ISSUE TITLE
KLU wrappers

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/LinearSolve.jl#9]
https://ufdc.ufl.edu/UFE0011721/00001

@andreasnoack @ViralBShah is KLU wrapped in Julia? How would it be accessed through the SuiteSparse wrappers?

**Comment by ViralBShah** [comment]
Probably not - but can't be more than an afternoon's work. Pinging @Wimmerer to see if he may be able to help.

**Comment by Wimmerer** [comment]
I plan to be sure we have complete SuiteSparse coverage this coming week. If it's in there I'll be sure we have it.

**Comment by ViralBShah** [comment]
Yes, KLU is in SuiteSparse:
https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/master/KLU

It is also perhaps no more than a few days of work to have a native Julia implementation of KLU, which would be very valuable.

**Comment by Wimmerer** [comment]
If it's just a few days work I can also do a Julia implementation. But for now expect to see a wrapper towards the end of next week. It'll probably come out with 1.0 of SuiteSparseGraphBLAS.jl

**Comment by Wimmerer** [comment]
Is there a way to assign this issue to me?

**Comment by ViralBShah** [comment]
> If it's just a few days work I can also do a Julia implementation

For whoever does this and whenever, the thesis linked above talks about the algorithm. It is basically a straightforward left looking LU. IIRC, it was found that circuit matrices were too unstructured, and all the supernodal and multifrontal methods spent a lot of time looking for structure that didn't exist, and ended up being slow. Having a good implementation of the textbook sparse LU method is what you need. That's what KLU does. If you read the C code, it is pretty compact.

**Comment by ViralBShah** [comment]
@Wimmerer Are your complete SuiteSparse wrappers going into SuiteSparse.jl or a separate package? Are you auto-generating them with Clang.jl?

**Comment by Wimmerer** [comment]
We discussed this in Slack but for records. The plan is to fork SuiteSparse.jl and auto-generate *all* rather than just some functions. I imagine it will be very time consuming to make Julian wrappers for each function, but I'll start with this capability. 

Merging that fork back will depend on 1. Maintaining all current capability, and 2. The timeline for making SuiteSparse.jl a package. 

If that can happen quickly then we can probably provide KLU fairly soon. If not we may want to create a temporary package so it's accessible.

**Comment by ChrisRackauckas** [comment]
Hey @Wimmerer, any update here? See the way the other factorization wrappers are handled.

**Comment by Wimmerer** [comment]
I'm going to add KLU.jl to the registry today or tomorrow, so after the 3 day waiting period I'll make a PR here.

It was originally going to be part of SuiteSparse.jl, but it was decided to do separately a few days ago.

**Comment by ChrisRackauckas** [comment]
Now it's got a repo https://github.com/JuliaSparse/KLU.jl 🎉

**Comment by ChrisRackauckas** [comment]
Completed via https://github.com/SciML/LinearSolve.jl/pull/44
